master:
  build: .
  environment:
    JAVA_OPTS: "-Dfile.encoding=UTF8 -Duser.timezone=UTC -Dmail.smtp.starttls.enable=true -Dhudson.DNSMultiCast.disabled=true -Dhudson.udp=-1 -Djava.awt.headless=true"
  ports:
    # - "50000:50000"
    - "8080:8080"
  volumes:
    - /var/jenkins_home
